### ISSUE TITLE
About the model processing input images of different sizes

### ISSUE THREAD

**Issue by eaymoney** [buggyyang/CDC_compression#20]
Very impressive work.
The model works fine when the length and width are multiples of 64. But when it is processed with other multiples, such as multiples of 16, it will report an error. I would like to ask how I can solve the problem when I want to process images with a length and width of 16, such as 144*144?

Traceback (most recent call last):
  File "/root/CDC_compression-main/epsilonparam/test_epsilonparam.py", line 84, in <module>
    main(args.device)
  File "/root/CDC_compression-main/epsilonparam/test_epsilonparam.py", line 70, in main
    compressed, bpp = diffusion.compress(
  File "/root/anaconda3/envs/CDC/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/CDC_compression-main/epsilonparam/modules/denoising_diffusion.py", line 205, in compress
    context_dict = self.context_fn(images, bitrate_scale)
  File "/root/anaconda3/envs/CDC/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/CDC_compression-main/epsilonparam/modules/compress_modules.py", line 101, in forward
    q_latent, q_hyper_latent, state4bpp = self.encode(input, cond)
  File "/root/CDC_compression-main/epsilonparam/modules/compress_modules.py", line 66, in encode
    q_latent = quantize(latent, "dequantize", latent_distribution.mean)
  File "/root/CDC_compression-main/epsilonparam/modules/utils.py", line 86, in quantize
    return round_w_offset(x, offset)
  File "/root/CDC_compression-main/epsilonparam/modules/utils.py", line 76, in round_w_offset
    diff = STERound.apply(input - loc)
RuntimeError: The size of tensor a (11) must match the size of tensor b (12) at non-singleton dimension 3

**Comment by buggyyang** [comment]
You need to pad the images with black pixels to handle this (pad 144 to 192). Note that when calculating bpp, you need to use the original image size.
